"""Added balance column

Revision ID: 575bfef46f18
Revises: 58902e0b5a8c
Create Date: 2024-02-17 07:41:23.556956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '575bfef46f18'
down_revision = '58902e0b5a8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('balance')

    # ### end Alembic commands ###
